####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [STATE_CODE_2016, SA3_CODE_2016, SA2_MAINCODE_2016, SA1_7DIGITCODE_2016]
seed_geography: SA3_CODE_2016


# Tracing
# ------------------------------------------------------------------
trace_geography:
  SA1: 2100101
  SA2: 201011001

  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : h_test_seed.csv
    index_col: hh_id
    rename_columns:
      hhnum: hh_id
      HomeSA1: SA1_7DIGITCODE_2016
      HomeSA2: SA2_MAINCODE_2016
      HomeSA3: SA3_CODE_2016
      HomeSA4: SA4_CODE_2016
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : p_test_seed.csv
    rename_columns:
      # SERIALNO: hh_id
      hhnum: hh_id
      HomeSA1: SA1_7DIGITCODE_2016
      HomeSA2: SA2_MAINCODE_2016
      HomeSA3: SA3_CODE_2016
      HomeSA4: SA4_CODE_2016
    # drop unused mixed type fields to avoid PyTables pipeline performance issues
    # (PyTables will pickle object types that it cannot map directly to c-types)
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
  - tablename: SA1_7DIGITCODE_2016_control_data
    filename : SA1_controls.csv
  - tablename: SA2_MAINCODE_2016_control_data
    filename : SA2_controls.csv
  - tablename: SA3_CODE_2016_control_data
    filename : SA3_controls.csv
  - tablename: STATE_CODE_2016_control_data
    filename : STATE_all_control.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: CW_ADHHWGT_SA3
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_SA1
    - summary_SA2
    - summary_SA1_SA3
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - HHSIZE
      - CARS
  persons:
    filename: synthetic_persons.csv
    columns:
      - AGE
      - SEX
      - ANYWORK


# Model steps for base mode
# ------------------------------------------------------------------
models:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=SA2_MAINCODE_2016
    - sub_balancing.geography=SA1_7DIGITCODE_2016
    - expand_households
    - write_data_dictionary
    - summarize
    - write_tables
    - write_synthetic_population

resume_after:
